### ISSUE TITLE
Tests fail after commit b0e3ce1 on ubuntu 12.04.2

### ISSUE THREAD

**Issue by Hettomei** [sporkmonger/uuidtools#22]
Hi,

I open a new issue since the rspec output as changed (from this previous issue https://github.com/sporkmonger/uuidtools/issues/12 ): 

I copy paste the entire output : 

``` shell
Warning: cannot open /proc/net/dev (No such file or directory). Limited output.
F...............*............Warning: cannot open /proc/net/dev (No such file or directory). Limited output.
F..................F...............

Pending:
  UUIDTools::UUID before obtaining a MAC address should return the output of the ifconfig program
    # I'm not quite sure how to mock backticks
    # ./spec/uuidtools/mac_address_spec.rb:418

Failures:

  1) UUIDTools::UUID when obtaining a MAC address should obtain a MAC address
     Failure/Error: @mac_address.should_not be_nil
       expected: not nil
            got: nil
     # ./spec/uuidtools/mac_address_spec.rb:243:in `block (2 levels) in <top (required)>'

  2) UUIDTools::UUID when generating should correctly generate timestamp variant UUIDs
     Failure/Error: UUIDTools::UUID.timestamp_create.should_not be_random_node_id
       expected random_node_id? to return false, got true
     # ./spec/uuidtools/uuid_creation_spec.rb:17:in `block (2 levels) in <top (required)>'

  3) UUIDTools::UUID when parsing should not treat a timestamp version UUID as a random node UUID
     Failure/Error: UUIDTools::UUID.timestamp_create.should_not be_random_node_id
       expected random_node_id? to return false, got true
     # ./spec/uuidtools/uuid_parsing_spec.rb:27:in `block (2 levels) in <top (required)>'

Finished in 0.1865 seconds
64 examples, 3 failures, 1 pending

Failed examples:

rspec ./spec/uuidtools/mac_address_spec.rb:241 # UUIDTools::UUID when obtaining a MAC address should obtain a MAC address
rspec ./spec/uuidtools/uuid_creation_spec.rb:16 # UUIDTools::UUID when generating should correctly generate timestamp variant UUIDs
rspec ./spec/uuidtools/uuid_parsing_spec.rb:26 # UUIDTools::UUID when parsing should not treat a timestamp version UUID as a random node UUID
```

**Comment by sporkmonger** [comment]
closed as stale
